config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'

  get 'download', to: 'quotes#download', as: :download_quotes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true

  serialize :custom_meta, Hash

  class << self
    def download_and_save!
      response = RestClient.get('http://quotesondesign.com/wp-json/posts?filter[orderby]=rand&filter[posts_per_page]=10')
      quotes = JSON.parse(response.body)
      quotes.each do |quote|
        Quote.create(title: quote['title'], content: quote['content'], link: quote['link'], custom_meta: quote['custom_meta'])
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = Quote.all
  end

  def download
    begin
      Quote.download_and_save!
      flash[:notice] = 'Downloaded and saved successfully!'
    rescue
      flash[:error] = "Couldn't download the quotes due to internal server error(500)"
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quote App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<h1>Quotes</h1>
<h2><%= link_to 'Download quotes', download_quotes_path %></h2>
<% if @quotes.present? %>
  <table>
    <thead>
      <th>ID</th>
      <th>Title</th>
      <th>Content</th>
      <th>Link</th>
      <th>Custom Meta</th>
    </thead>
    <tbody>
      <%@quotes.each do |quote|%>
        <tr>
          <td><%=quote.id%></td>
          <td><%=quote.title%></td>
          <td><%=quote.content.html_safe%></td>
          <td><%=link_to quote.link, quote.link%></td>
          <td><%=quote.custom_meta%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
<%else%>
  <h2>These is no quote at the moment!</h2>
<%end%>